version: "3.5"
services:
  gofizzbuzz:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    volumes:
      - ./server_data/:/app/server_data/:rw
  prometheus:
    image: prom/prometheus:v2.9.2
    user: "root"
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--storage.tsdb.retention=1y'
    restart: always
  grafana:
    image: grafana/grafana:6.1.6
    user: "root"
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: always
